# Generated by Django 5.1.1 on 2024-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SDE', 'softwareDeveloper'), ('Hr', 'HR'), ('Salesman', 'Salesman'), ('Intern', 'Intern')], max_length=20),
        ),
    ]
